# Site settings
author: Rabiah Hogans
title: “Why I decided to study Software Engineering?"
header-img: img/home-bg.png
email: hogansrabiah@gmail.com
copyright_name: Rabiah Hogans
description: > # this means to ignore newlines until "baseurl:"
  Making the right choice
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rbhogans

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
